### PR TITLE
Update Shopgate Plugin to version 2.9.52

### PR DESCRIPTION
**Pull request by OliverMuellerShopgate**
Update Shopgate Plugin to version 2.9.52

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @OliverMuellerShopgate,

The third version in less than one month, you never stop. :)
I see that you add a weight and a price range to our new Carrier. But what if the module has been already created ? Do you also want to apply them on the existing carriers ?

**Comment by OliverMuellerShopgate** [comment]
Hi @Quetzacoalt91 

We plan to update the Plugin at least every two weeks.
I updated the pull request (we added a file upgrade/Upgrade-2.9.52.php and this should handle updated plugins as well. Thanks for noticing ;)

**Comment by OliverMuellerShopgate** [comment]
Hi @Quetzacoalt91 ,

we just got a bug report and I added a small hotfix to this pull request. This will be our final version. I would appriciate if you take a quick look at it. Thanks :)

**Comment by Quetzacoalt91** [comment]
Hi @OliverMuellerShopgate,

Here we go, the PR has just been merged and the changes will be available soon.

Best regards

**Comment by OliverMuellerShopgate** [comment]
Hi @Quetzacoalt91,

that was fast. thanks a lot!

Best regards

**Pull request merged**
