### PR TITLE
Update to version 2.9.50

### PR DESCRIPTION
**Pull request by OliverMuellerShopgate**
Update to version 2.9.50

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @OliverMuellerShopgate,

For the PR #5 we have already bumped the module to the version 2.9.50. You should upgrade it to 2.9.51 in order to suggest the update in the Back-offices.

**Comment by OliverMuellerShopgate** [comment]
@Quetzacoalt91 This will cause problems in our system. if you want to change something please give us the code you want to have changed. We will create a pull request for that and take care of the versioning. What will we do now? We have to set the version to 2.9.51?

**Comment by Quetzacoalt91** [comment]
Hi,

I note that for the next PR @OliverMuellerShopgate.
But for this time, you have to set the version to 2.9.51.

**Comment by OliverMuellerShopgate** [comment]
@Quetzacoalt91 I changed the plugin version and added the missing translation files

**Comment by Quetzacoalt91** [comment]
Thanks @OliverMuellerShopgate, the PR will be merged next Monday !

**Comment by Quetzacoalt91** [comment]
Hi @OliverMuellerShopgate,

Your PR has just been merged and the changes should be available from tomorrow.

Best regards

**Pull request merged**
